version: '3.8'

services:
  python-coach:
    build: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./data:/data  # Persistent storage for database
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep python | grep bot.py || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Uncomment for production with Redis
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   volumes:
  #     - redis_data:/data

# volumes:
#   redis_data: